### PR TITLE
Ukrainian language support

### PR DESCRIPTION
**Pull request by NeonMariia**

### CODE REVIEW

**Comment by JarbasAl** [comment]
not sure how I can review this, would be nice to have someone else that speaks the language reviewing the unittests

@NeonMariia I assume this is a work in progress since there's a lot of commented unittests and the github actions are failing, let me know if i can help somehow

**Comment by NeonDaniel** [comment]
Marked as draft until this is completed. When completed, we can tag another Ukrainian speaker at Neon to review tests unless there's a community member who is able to review.

**Comment by JarbasAl** [comment]
if it helps this PR can be broken into different ones, its ok to have several PRs each adding a different method

since #46 we now track methods per language, and most of them do not have all methods implemented yet

**Comment by NeonMariia** [comment]
> if it helps this PR can be broken into different ones, its ok to have several PRs each adding a different method
> 
> since #46 we now track methods per language, and most of them do not have all methods implemented yet

That's what we were discussing recently. I think it would be great!

**Comment by NeonDaniel** [comment]
Replaced by #50, #51 ?

**Pull request closed without merging**
