### PR TITLE
expand DE yes no alternatives

### PR DESCRIPTION
**Pull request by emphasize**

### CODE REVIEW

**Comment by emphasize** [comment]
Have to sleep over it, maybe rearrange (esp. bc those double negatives) and add some Tests

**Comment by JarbasAl** [comment]
> Have to sleep over it, maybe rearrange (esp. bc those double negatives) and add some Tests

please add tests for the use cases this is covering, being your native language you are the authority, we can only review tests and trust you on the language side

**Comment by emphasize** [comment]
generally hard to compute sarcasm/irony.
additionally we usually prefix like "not impossible" (ie. un-*)
The question should be clear cut on the skill side

**Comment by emphasize** [comment]
Maybe we should allow a dict to be passed and merged with the default, so we can assure better contextual accuracy.
We could use the  `data`  that is already part of the signature

**Pull request merged**
